{"name": "Проверка невозможности принять заказ при некорректном ID курьера", "status": "passed", "start": 1732976695046, "stop": 1732976695358, "uuid": "f59a4b73-946a-479b-9dba-1614a5e19ac3", "historyId": "2187d1c5696e9555d5238263e2dc35ad", "testCaseId": "2187d1c5696e9555d5238263e2dc35ad", "fullName": "tests.test_take_order.TestTakeOrder#test_take_order_uncorrect_courier_id_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_take_order"}, {"name": "subSuite", "value": "TestTakeOrder"}, {"name": "host", "value": "DESKTOP-4GFTOQP"}, {"name": "thread", "value": "10124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_take_order"}]}