{"name": "Проверка невозможности возврата заказа при отсутствии трек-номера в запросе", "status": "passed", "start": 1732976692926, "stop": 1732976692971, "uuid": "ed5c3b45-51b8-45a5-88a1-a5bb1eee18b3", "historyId": "3779ac802dfa1801a6a6569863cc658c", "testCaseId": "3779ac802dfa1801a6a6569863cc658c", "fullName": "tests.test_get_order_by_num.TestGetOrderByNum#test_get_order_without_num_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order_by_num"}, {"name": "subSuite", "value": "TestGetOrderByNum"}, {"name": "host", "value": "DESKTOP-4GFTOQP"}, {"name": "thread", "value": "10124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_by_num"}]}